### ISSUE TITLE
Allow custom SWA config

### ISSUE THREAD

**Issue by geoffrich** [geoffrich/svelte-adapter-azure-swa#1]
We should allow the user to extend the [default SWA config](https://github.com/geoffrich/svelte-adapter-azure-swa/blob/5f4492b9f73b2871c9a62c5f19f11a45b8bffece/files/staticwebapp.config.json) to add custom redirects, auth, etc.

Potentially, allow the user to create a config in the root directly and merge it with the default config. We should error on overriding `navigationFallback` since this is critical for the SSR functionality and endpoints. Other redirects can be added so long as the catch-all redirect for post/put/delete is at the end. Non-routing settings can be copied over as-is.

This file should be named differently so that the deployment picks up the generated config.

**Comment by biltongza** [comment]
Perhaps this can be a config passed in to the adapter instead of its own file? In my head it should be simple enough to do that then merge the passed in config with the generated config (checking for anything that overrides critical routing of course). If you're happy with that approach I could probably try whip up a PR for it at some point.

**Comment by geoffrich** [comment]
I agree, I think a config value makes more sense here. A PR would be welcome!
