### ISSUE TITLE
Build error about cookies

### ISSUE THREAD

**Issue by Abbbdab** [geoffrich/svelte-adapter-azure-swa#118]
Currently trying to build and deploy and I keep getting error:

.svelte-kit/azure-tmp/headers.js:1:35: ERROR: Could not resolve "set-cookie-parser"

**Comment by geoffrich** [comment]
Hey, I can't reproduce this -- I just re-deployed the demo app with the latest SvelteKit version and everything worked (https://github.com/geoffrich/svelte-adapter-azure-swa/pull/119). Can you provide a sample repo that reproduces the issue?

**Comment by geoffrich** [comment]
@derekhearst Seems like it's related to using pnpm somehow: https://github.com/geoffrich/svelte-adapter-azure-swa/pull/119#issuecomment-1449782381

I'm on vacation at the moment and can't troubleshoot right away, but maybe that can help find a workaround. Not sure why using pnpm would break things.

**Comment by tlaundal** [comment]
It seems you can work around this by adding `set-cookie-parser` as a dependency to the project.

I *think* the issue is that pnpm (and also yarn in pnp mode) is more strict about exposing modules only to the projects that actually require them. The build process happens inside `.svelte-kit/azure-tmp`, which thus doesn't necessarily have the dependency of the adapter available. This is just a theory, and I haven't validated or done more research to check this.

I wonder if it might work to declare `set-cookie-parser` as a peer-dependency of the adapter. Though I'm not sure if this necessarily forces the dependency to be hoisted, or only ensures the version will be the same.

**Comment by derekhearst** [comment]
I can confirm that adding `set-cookie-parser` as a dependency  does let the build work. Thanks for the help on this : )
