### ISSUE TITLE
Deploying app with +server.ts or routes/[slug]/+page.svelte

### ISSUE THREAD

**Issue by maxmalynowsky** [geoffrich/svelte-adapter-azure-swa#166]
I'm having some difficulty getting [dynamic pages](https://kit.svelte.dev/docs/routing#page) and [server APIs](https://kit.svelte.dev/docs/routing#server) provided by SvelteKit from working on Azure Static Web Apps. I have successfully deployed an app to CloudFlare Pages with `adapter-auto` and both features working there. When I deploy to Static Web Apps, both dynamic pages and server APIs give 404 errors when trying to access them. Only the `+page.svelte` with a `+layout.ts` containing `export const prerender = true;` are rendered.

I noticed that the demo app doesn't include either of these, would it be possible to add them so I can see what I might be doing wrong on my end? If neither of these are supported with the current adapter, that would be helpful to know as well.

**Comment by maxmalynowsky** [comment]
I just noticed that I'm missing the correct `staticwebapp.config.json` options in my custom config referenced in https://github.com/geoffrich/svelte-adapter-azure-swa/issues/1. Mentioning this could be helpful to add to the README!

**Comment by geoffrich** [comment]
What else would you like to see mentioned in the README that isn't covered by the [customStaticWebAppConfig docs](https://github.com/geoffrich/svelte-adapter-azure-swa#customstaticwebappconfig)?

PRs welcome!

**Comment by jaycoolslm** [comment]
I'm a bit confused here - am at a similar sticking point re my /api directory with my routes.

Should I refactor to use only form actions? Or is it possible to tinker with customStaticWebAppConfig in order to get my current /api routes to work... not that clear to me. If that is possible, an example would be incredibly useful

**Comment by geoffrich** [comment]
@jaycoolslm are you saying that you have other Azure functions under /api that you want to call? In that case, look into the [apiDir](https://github.com/geoffrich/svelte-adapter-azure-swa?tab=readme-ov-file#apidir) option.

If you are still having trouble, please open a new issue with an example of what you're trying to do. I'll close this issue since the original post was resolved.

**Comment by jaycoolslm** [comment]
Yes - exactly that. 

So essentially all I need to do is rename '/api' e.g. to '/svelteApi' (so it doesn't cause the build error), and then pass in apiDir: '/svelteApi'?
