### ISSUE TITLE
Move demo app into repo

### ISSUE THREAD

**Issue by geoffrich** [geoffrich/svelte-adapter-azure-swa#69]
Move the [demo app](https://github.com/geoffrich/sveltekit-azure-swa-demo) into this repo. This will allow us to more easily test adapter changes before releasing a new version. The demo should import the adapter directly instead of installing from npm.

This could also enable E2E tests on PRs.

We should be able to kick off a preview build for each PR (though maybe it should be configurable, since the preview notifications can be noisy.)

**Comment by FlippingBinary** [comment]
I see there is a `__layout.svelte` in that demo app, which is from the old routing method. Would it be okay to build a new demo app with the latest version of SvelteKit instead of copying the existing one? There are no more planned breaking changes in SvelteKit since https://github.com/sveltejs/kit/pull/6707, so it's stable enough now that it makes sense to rebuild.

**Comment by geoffrich** [comment]
Yeah, it would be cleanest to just regenerate the demo app with `npm create svelte@latest` instead of copying things over. The demo in that repo is pretty much just the default Kit demo with some adapter config anyway.

I had opened https://github.com/geoffrich/sveltekit-azure-swa-demo/pull/8 to update to the latest Kit (as of a few weeks ago), but that PR can probably be closed if we're moving it into this repo anyway.

**Comment by geoffrich** [comment]
Re: auto-running the demo app deployment: possibly automatically deploy a preview for each autorelease PR (e.g. #76) and also allow manually doing a deployment.
